// @ts-check
/**
 * TrafficScout tenant taxonomy — versioned category definitions.
 *
 * This module is the single authoritative definition of business categories and
 * their configurable attribute profiles. It is pure data + no I/O so it can be
 * imported by the client, the server pipeline, tests, and the DB seed script.
 *
 * Rules:
 * - Never hard-code category assumptions elsewhere in the app; read them here
 *   (or from the `category_profiles` table, which is seeded from this file and
 *   may be overridden per methodology version).
 * - Bump TAXONOMY_VERSION on any change to slugs or profile semantics.
 */

export const TAXONOMY_VERSION = "1.0.0";

/**
 * Broad sectors. Slugs are stable identifiers; display names may change.
 * @type {ReadonlyArray<{slug: string, name: string}>}
 */
export const SECTORS = Object.freeze([
  { slug: "food_beverage", name: "Food & Beverage" },
  { slug: "grocery_specialty_food", name: "Grocery & Specialty Food" },
  { slug: "personal_services", name: "Personal Services" },
  { slug: "medical", name: "Medical" },
  { slug: "dental", name: "Dental" },
  { slug: "veterinary_pet", name: "Veterinary & Pet Services" },
  { slug: "fitness_wellness", name: "Fitness & Wellness" },
  { slug: "beauty", name: "Beauty" },
  { slug: "childcare_education", name: "Childcare & Education" },
  { slug: "entertainment", name: "Entertainment" },
  { slug: "general_retail", name: "General Retail" },
  { slug: "specialty_retail", name: "Specialty Retail" },
  { slug: "financial_services", name: "Financial Services" },
  { slug: "professional_services", name: "Professional Services" },
  { slug: "automotive", name: "Automotive" },
  { slug: "home_services", name: "Home Services" },
  { slug: "government_community", name: "Government & Community" },
  { slug: "office", name: "Office Uses" },
  { slug: "flex_coworking", name: "Flexible & Coworking" },
]);

/**
 * @typedef {"low"|"medium"|"high"} Level
 * @typedef {"morning"|"midday"|"afternoon"|"evening"|"weekend"} Daypart
 *
 * @typedef {Object} CategoryProfile
 * @property {[number, number]} typicalSqftRange   Typical unit size in sqft [min, max].
 * @property {Daypart[]} preferredDayparts         Traffic periods the use depends on.
 * @property {"destination"|"convenience"|"mixed"} orientation
 * @property {Level} parkingDemand
 * @property {Level} visibilitySensitivity
 * @property {Level} incomeSensitivity
 * @property {Level} daytimePopulationSensitivity
 * @property {Level} residentialDensitySensitivity
 * @property {Level} familyHouseholdSensitivity
 * @property {Level} competitionTolerance          High = clusters happily (e.g. restaurants).
 * @property {string[]} cotenancyPreferences       Category/sector slugs that drive cross-shopping.
 * @property {string[]} physicalRequirements       Tokens from PHYSICAL_REQUIREMENTS.
 * @property {Level} rentTolerance                 Ability to pay top-of-market rents.
 * @property {"daily"|"weekly"|"monthly"|"occasional"} visitFrequency
 *
 * @typedef {Object} Category
 * @property {string} slug
 * @property {string} name
 * @property {string} sector      Slug from SECTORS.
 * @property {CategoryProfile} profile
 */

/**
 * Physical-requirement tokens used by vacancy-compatibility rules.
 * A vacancy either satisfies, fails, or is `unknown` for each token.
 */
export const PHYSICAL_REQUIREMENTS = Object.freeze([
  "venting", // Type-1 hood / kitchen exhaust
  "grease_trap",
  "drive_through",
  "high_ceiling",
  "outdoor_area", // patio / play yard
  "heavy_parking",
  "loading_access",
  "plumbing_intensive", // salons, medical, laundromats
  "end_cap_or_pad", // strongly prefers end-cap/pad placement
  "ada_ground_floor",
]);

/** @type {ReadonlyArray<Category>} */
export const CATEGORIES = Object.freeze([
  // ── Food & Beverage ────────────────────────────────────────────────────────
  {
    slug: "quick_service_restaurant",
    name: "Quick-Service Restaurant",
    sector: "food_beverage",
    profile: {
      typicalSqftRange: [1200, 3000],
      preferredDayparts: ["midday", "evening"],
      orientation: "convenience",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "high",
      cotenancyPreferences: ["grocery_anchor", "fitness_center", "general_retail"],
      physicalRequirements: ["venting", "grease_trap"],
      rentTolerance: "high",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "fast_casual_restaurant",
    name: "Fast-Casual Restaurant",
    sector: "food_beverage",
    profile: {
      typicalSqftRange: [1800, 3500],
      preferredDayparts: ["midday", "evening", "weekend"],
      orientation: "mixed",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "high",
      cotenancyPreferences: ["grocery_anchor", "boutique_fitness", "coffee_shop"],
      physicalRequirements: ["venting", "grease_trap"],
      rentTolerance: "high",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "full_service_restaurant",
    name: "Full-Service Restaurant",
    sector: "food_beverage",
    profile: {
      typicalSqftRange: [3000, 6500],
      preferredDayparts: ["evening", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "medium",
      incomeSensitivity: "high",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["entertainment_venue", "specialty_retail_general"],
      physicalRequirements: ["venting", "grease_trap", "heavy_parking"],
      rentTolerance: "medium",
      visitFrequency: "monthly",
    },
  },
  {
    slug: "coffee_shop",
    name: "Coffee Shop / Café",
    sector: "food_beverage",
    profile: {
      typicalSqftRange: [800, 2200],
      preferredDayparts: ["morning", "midday"],
      orientation: "convenience",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "medium",
      cotenancyPreferences: ["fitness_center", "boutique_fitness", "office_professional"],
      physicalRequirements: ["end_cap_or_pad"],
      rentTolerance: "high",
      visitFrequency: "daily",
    },
  },
  {
    slug: "bar_taproom",
    name: "Bar / Taproom",
    sector: "food_beverage",
    profile: {
      typicalSqftRange: [1800, 4500],
      preferredDayparts: ["evening", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "high",
      cotenancyPreferences: ["full_service_restaurant", "entertainment_venue"],
      physicalRequirements: ["outdoor_area"],
      rentTolerance: "medium",
      visitFrequency: "weekly",
    },
  },

  // ── Grocery & Specialty Food ───────────────────────────────────────────────
  {
    slug: "grocery_anchor",
    name: "Grocery Anchor",
    sector: "grocery_specialty_food",
    profile: {
      typicalSqftRange: [25000, 65000],
      preferredDayparts: ["midday", "afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: [],
      physicalRequirements: ["heavy_parking", "loading_access", "high_ceiling"],
      rentTolerance: "low",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "specialty_food_market",
    name: "Specialty / Ethnic Food Market",
    sector: "grocery_specialty_food",
    profile: {
      typicalSqftRange: [2500, 12000],
      preferredDayparts: ["afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["grocery_anchor"],
      physicalRequirements: ["loading_access"],
      rentTolerance: "low",
      visitFrequency: "weekly",
    },
  },

  // ── Personal Services ──────────────────────────────────────────────────────
  {
    slug: "dry_cleaner_laundry",
    name: "Dry Cleaner / Laundry",
    sector: "personal_services",
    profile: {
      typicalSqftRange: [1000, 3000],
      preferredDayparts: ["morning", "afternoon"],
      orientation: "convenience",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "low",
      cotenancyPreferences: ["grocery_anchor"],
      physicalRequirements: ["plumbing_intensive"],
      rentTolerance: "low",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "tailor_shoe_repair",
    name: "Tailor / Repair Services",
    sector: "personal_services",
    profile: {
      typicalSqftRange: [500, 1500],
      preferredDayparts: ["midday", "afternoon"],
      orientation: "convenience",
      parkingDemand: "low",
      visibilitySensitivity: "low",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "low",
      cotenancyPreferences: ["dry_cleaner_laundry"],
      physicalRequirements: [],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },

  // ── Medical / Dental / Vet ─────────────────────────────────────────────────
  {
    slug: "urgent_care",
    name: "Urgent Care Clinic",
    sector: "medical",
    profile: {
      typicalSqftRange: [3000, 6000],
      preferredDayparts: ["morning", "midday", "afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "high",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["pharmacy", "grocery_anchor"],
      physicalRequirements: ["plumbing_intensive", "ada_ground_floor", "end_cap_or_pad"],
      rentTolerance: "high",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "pharmacy",
    name: "Pharmacy",
    sector: "medical",
    profile: {
      typicalSqftRange: [1800, 14000],
      preferredDayparts: ["midday", "afternoon"],
      orientation: "convenience",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["urgent_care", "medical_office", "grocery_anchor"],
      physicalRequirements: [],
      rentTolerance: "medium",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "medical_office",
    name: "Medical Office / Specialty Practice",
    sector: "medical",
    profile: {
      typicalSqftRange: [1500, 5000],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "low",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["pharmacy", "dental_practice"],
      physicalRequirements: ["plumbing_intensive", "ada_ground_floor"],
      rentTolerance: "medium",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "dental_practice",
    name: "Dental Practice",
    sector: "dental",
    profile: {
      typicalSqftRange: [1500, 3500],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["medical_office", "pharmacy"],
      physicalRequirements: ["plumbing_intensive", "ada_ground_floor"],
      rentTolerance: "medium",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "veterinary_clinic",
    name: "Veterinary Clinic",
    sector: "veterinary_pet",
    profile: {
      typicalSqftRange: [2000, 5000],
      preferredDayparts: ["morning", "afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["pet_supply_grooming", "grocery_anchor"],
      physicalRequirements: ["plumbing_intensive"],
      rentTolerance: "medium",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "pet_supply_grooming",
    name: "Pet Supply / Grooming",
    sector: "veterinary_pet",
    profile: {
      typicalSqftRange: [1200, 8000],
      preferredDayparts: ["afternoon", "weekend"],
      orientation: "mixed",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["veterinary_clinic", "grocery_anchor"],
      physicalRequirements: ["plumbing_intensive"],
      rentTolerance: "medium",
      visitFrequency: "monthly",
    },
  },

  // ── Fitness & Wellness / Beauty ────────────────────────────────────────────
  {
    slug: "fitness_center",
    name: "Fitness Center / Gym",
    sector: "fitness_wellness",
    profile: {
      typicalSqftRange: [8000, 30000],
      preferredDayparts: ["morning", "evening", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "low",
      cotenancyPreferences: ["coffee_shop", "fast_casual_restaurant"],
      physicalRequirements: ["high_ceiling", "heavy_parking", "plumbing_intensive"],
      rentTolerance: "low",
      visitFrequency: "daily",
    },
  },
  {
    slug: "boutique_fitness",
    name: "Boutique Fitness Studio",
    sector: "fitness_wellness",
    profile: {
      typicalSqftRange: [1500, 4000],
      preferredDayparts: ["morning", "evening", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "high",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["coffee_shop", "salon_spa", "fast_casual_restaurant"],
      physicalRequirements: ["plumbing_intensive"],
      rentTolerance: "medium",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "salon_spa",
    name: "Salon / Spa",
    sector: "beauty",
    profile: {
      typicalSqftRange: [1000, 3500],
      preferredDayparts: ["midday", "afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "high",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["boutique_fitness", "nail_salon"],
      physicalRequirements: ["plumbing_intensive"],
      rentTolerance: "medium",
      visitFrequency: "monthly",
    },
  },
  {
    slug: "nail_salon",
    name: "Nail Salon",
    sector: "beauty",
    profile: {
      typicalSqftRange: [800, 2000],
      preferredDayparts: ["midday", "afternoon", "weekend"],
      orientation: "convenience",
      parkingDemand: "low",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "low",
      cotenancyPreferences: ["salon_spa", "grocery_anchor"],
      physicalRequirements: ["plumbing_intensive", "venting"],
      rentTolerance: "medium",
      visitFrequency: "monthly",
    },
  },

  // ── Childcare, Education, Entertainment ────────────────────────────────────
  {
    slug: "childcare_center",
    name: "Childcare / Early Education",
    sector: "childcare_education",
    profile: {
      typicalSqftRange: [3000, 10000],
      preferredDayparts: ["morning", "afternoon"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "low",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["grocery_anchor", "kids_activity_center"],
      physicalRequirements: ["outdoor_area", "ada_ground_floor", "plumbing_intensive"],
      rentTolerance: "low",
      visitFrequency: "daily",
    },
  },
  {
    slug: "tutoring_enrichment",
    name: "Tutoring / Enrichment",
    sector: "childcare_education",
    profile: {
      typicalSqftRange: [1000, 2500],
      preferredDayparts: ["afternoon", "evening", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "low",
      incomeSensitivity: "high",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "medium",
      cotenancyPreferences: ["kids_activity_center", "grocery_anchor"],
      physicalRequirements: [],
      rentTolerance: "medium",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "kids_activity_center",
    name: "Kids' Activity Center",
    sector: "entertainment",
    profile: {
      typicalSqftRange: [4000, 15000],
      preferredDayparts: ["afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "low",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "low",
      cotenancyPreferences: ["fast_casual_restaurant", "childcare_center"],
      physicalRequirements: ["high_ceiling", "heavy_parking"],
      rentTolerance: "low",
      visitFrequency: "weekly",
    },
  },
  {
    slug: "entertainment_venue",
    name: "Entertainment Venue",
    sector: "entertainment",
    profile: {
      typicalSqftRange: [6000, 40000],
      preferredDayparts: ["evening", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["full_service_restaurant", "bar_taproom"],
      physicalRequirements: ["high_ceiling", "heavy_parking"],
      rentTolerance: "low",
      visitFrequency: "monthly",
    },
  },

  // ── Retail ─────────────────────────────────────────────────────────────────
  {
    slug: "general_retail",
    name: "General Retail",
    sector: "general_retail",
    profile: {
      typicalSqftRange: [1500, 10000],
      preferredDayparts: ["midday", "afternoon", "weekend"],
      orientation: "mixed",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: ["grocery_anchor"],
      physicalRequirements: [],
      rentTolerance: "medium",
      visitFrequency: "monthly",
    },
  },
  {
    slug: "specialty_retail_general",
    name: "Specialty Retail",
    sector: "specialty_retail",
    profile: {
      typicalSqftRange: [1000, 4000],
      preferredDayparts: ["afternoon", "weekend"],
      orientation: "destination",
      parkingDemand: "low",
      visibilitySensitivity: "medium",
      incomeSensitivity: "high",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "medium",
      cotenancyPreferences: ["coffee_shop", "full_service_restaurant"],
      physicalRequirements: [],
      rentTolerance: "medium",
      visitFrequency: "occasional",
    },
  },

  // ── Financial / Professional / Auto / Home ─────────────────────────────────
  {
    slug: "bank_credit_union",
    name: "Bank / Credit Union",
    sector: "financial_services",
    profile: {
      typicalSqftRange: [2000, 5000],
      preferredDayparts: ["morning", "midday"],
      orientation: "convenience",
      parkingDemand: "medium",
      visibilitySensitivity: "high",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "low",
      cotenancyPreferences: ["grocery_anchor"],
      physicalRequirements: ["drive_through", "end_cap_or_pad"],
      rentTolerance: "high",
      visitFrequency: "monthly",
    },
  },
  {
    slug: "insurance_tax_office",
    name: "Insurance / Tax Office",
    sector: "financial_services",
    profile: {
      typicalSqftRange: [800, 2000],
      preferredDayparts: ["midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "low",
      visibilitySensitivity: "low",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "medium",
      cotenancyPreferences: [],
      physicalRequirements: [],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "office_professional",
    name: "Professional Services Office",
    sector: "professional_services",
    profile: {
      typicalSqftRange: [1000, 4000],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "low",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "high",
      cotenancyPreferences: ["coffee_shop"],
      physicalRequirements: [],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "auto_parts_service",
    name: "Auto Parts / Service",
    sector: "automotive",
    profile: {
      typicalSqftRange: [3000, 8000],
      preferredDayparts: ["morning", "weekend"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "high",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "low",
      cotenancyPreferences: [],
      physicalRequirements: ["end_cap_or_pad", "loading_access"],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "home_improvement_services",
    name: "Home Services Showroom",
    sector: "home_services",
    profile: {
      typicalSqftRange: [1500, 6000],
      preferredDayparts: ["midday", "weekend"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "low",
      residentialDensitySensitivity: "high",
      familyHouseholdSensitivity: "high",
      competitionTolerance: "medium",
      cotenancyPreferences: ["general_retail"],
      physicalRequirements: ["loading_access"],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },

  // ── Government, Office, Flex ───────────────────────────────────────────────
  {
    slug: "government_community_use",
    name: "Government / Community Use",
    sector: "government_community",
    profile: {
      typicalSqftRange: [2000, 15000],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "high",
      visibilitySensitivity: "low",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "medium",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "medium",
      competitionTolerance: "low",
      cotenancyPreferences: [],
      physicalRequirements: ["ada_ground_floor", "heavy_parking"],
      rentTolerance: "low",
      visitFrequency: "occasional",
    },
  },
  {
    slug: "traditional_office",
    name: "Traditional Office",
    sector: "office",
    profile: {
      typicalSqftRange: [1000, 20000],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "low",
      incomeSensitivity: "low",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "low",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "high",
      cotenancyPreferences: ["coffee_shop", "fast_casual_restaurant"],
      physicalRequirements: [],
      rentTolerance: "low",
      visitFrequency: "daily",
    },
  },
  {
    slug: "coworking_flex",
    name: "Coworking / Flex Space",
    sector: "flex_coworking",
    profile: {
      typicalSqftRange: [3000, 20000],
      preferredDayparts: ["morning", "midday", "afternoon"],
      orientation: "destination",
      parkingDemand: "medium",
      visibilitySensitivity: "medium",
      incomeSensitivity: "medium",
      daytimePopulationSensitivity: "high",
      residentialDensitySensitivity: "medium",
      familyHouseholdSensitivity: "low",
      competitionTolerance: "low",
      cotenancyPreferences: ["coffee_shop", "fitness_center"],
      physicalRequirements: [],
      rentTolerance: "medium",
      visitFrequency: "daily",
    },
  },
]);
